<a href="https://colab.research.google.com/github/prabhnoor14/walmart-hurricane-project/blob/main/notebooks/team_notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [50]:
!git clone https://github.com/prabhnoor14/walmart-hurricane-project

fatal: destination path 'walmart-hurricane-project' already exists and is not an empty directory.

In [51]:
Decisions = []

def log_decision( decision, row_affected):
  Decisions.append({'decision': decision, 'rows': row_affected})
  print(f'{decision}({row_affected} row(s))')
def show_log():
  return pd.DataFrame(Decisions)

In [52]:
import pandas as pd

def load_table(PATH):
  try:
      df = pd.read_csv(PATH)
      df.head()
      return df
  except FileNotFoundError:
      print('File not found. Please check the file exist or double check the path')
      return None

In [53]:
def table_info(df):
  print('\nTable infor:')
  df.info()
  print('\nNull values for each column \n')
  print(df.isna().sum())                  # missing values per column
  print('\nDuplicated Rows Count: ',df.duplicated().sum())           # fully identical rows

In [54]:
walmart_transactions = load_table('/content/walmart-hurricane-project/data/walmart_transactions.csv')
table_info(walmart_transactions)

Table infor:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25562 entries, 0 to 25561
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   transaction_id  25562 non-null  object
 1   store_id        25562 non-null  object
 2   timestamp       24676 non-null  object
 3   sku             25562 non-null  object
 4   product_name    25562 non-null  object
 5   category        25562 non-null  object
 6   quantity        25562 non-null  int64
 7   unit_price      25562 non-null  object
dtypes: int64(1), object(7)
memory usage: 1.6+ MB

Null values for each column

transaction_id      0
store_id            0
timestamp         886
sku                 0
product_name        0
category            0
quantity            0
unit_price          0
dtype: int64

Duplicated Rows Count:  30

In [55]:
distribution_centers = load_table('/content/walmart-hurricane-project/data/distribution_centers.csv')
table_info(distribution_centers)

Table infor:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 8 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   dc_id                   5 non-null      object
 1   dc_name                 5 non-null      object
 2   city                    5 non-null      object
 3   state                   5 non-null      object
 4   avg_daily_shipments     5 non-null      int64
 5   surge_capacity          5 non-null      object
 6   distance_to_orlando_mi  5 non-null      int64
 7   cost_per_shipment       4 non-null      float64
dtypes: float64(1), int64(2), object(5)
memory usage: 452.0+ bytes

Null values for each column

dc_id                     0
dc_name                   0
city                      0
state                     0
avg_daily_shipments       0
surge_capacity            0
distance_to_orlando_mi    0
cost_per_shipment         1
dtype: int64

Duplicated Rows Count:  0

In [56]:
store_locations = load_table('/content/walmart-hurricane-project/data/store_locations.csv')
table_info(store_locations)

Table infor:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   store_id    14 non-null     object
 1   store_name  14 non-null     object
 2   city        14 non-null     object
 3   state       14 non-null     object
 4   zip_code    14 non-null     int64
 5   latitude    13 non-null     float64
 6   longitude   13 non-null     float64
 7   region      14 non-null     object
dtypes: float64(2), int64(1), object(5)
memory usage: 1.0+ KB

Null values for each column

store_id      0
store_name    0
city          0
state         0
zip_code      0
latitude      1
longitude     1
region        0
dtype: int64

Duplicated Rows Count:  0

In [57]:
product_catalog = load_table('/content/walmart-hurricane-project/data/product_catalog.csv')
table_info(product_catalog)

Table infor:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45 entries, 0 to 44
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sku           45 non-null     object
 1   product_name  45 non-null     object
 2   category      45 non-null     object
 3   subcategory   32 non-null     object
 4   unit_cost     40 non-null     float64
 5   supplier      45 non-null     object
 6   package_size  45 non-null     object
dtypes: float64(1), object(6)
memory usage: 2.6+ KB

Null values for each column

sku              0
product_name     0
category         0
subcategory     13
unit_cost        5
supplier         0
package_size     0
dtype: int64

Duplicated Rows Count:  0

In [58]:
def drop_duplicate(frame):
  clean = frame.drop_duplicates().copy() # saving a copy of the frame after dropping duplicates to not alter the original frame
  print('rows:', len(frame), '->', len(clean))
  return clean

In [59]:
print('Count of rows after dropping duplicated rows from the product_catalog table')
product_catalog_copy = drop_duplicate(product_catalog)
print('Count of rows after dropping duplicated rows from the walmart_transactions table')
walmart_transactions_copy = drop_duplicate(walmart_transactions)
print('Count of rows after dropping duplicated rows from the distribution_centers table')
distribution_centers_copy = drop_duplicate(distribution_centers)
print('Count of rows after dropping duplicated rows from the store_location table')
store_locations_copy = drop_duplicate(store_locations)

Count of rows after dropping duplicated rows from the product_catalog table
rows: 45 -> 45
Count of rows after dropping duplicated rows from the walmart_transactions table
rows: 25562 -> 25532
Count of rows after dropping duplicated rows from the distribution_centers table
rows: 5 -> 5
Count of rows after dropping duplicated rows from the store_location table
rows: 14 -> 14

In [60]:
def transform_price_columns(df, column_name):
  df[column_name] = (df[column_name].astype(str)
                     .str.replace('$','',regex=False)
                     .str.strip().astype(float))
  return df

In [61]:
transform_price_columns(walmart_transactions_copy, 'unit_price')

,transaction_id,store_id,timestamp,sku,product_name,category,quantity,unit_price
0,TXN012636,FL-710,2024-09-24T09:48:13,PNUTBTR-16,PEANUT BUTTER,Grocery,1,3.15
1,TXN000759,fl-412,2024-09-13 20:30:20,CNSOUP-01,CANNED SOUP,GROCERY,1,2.02
2,TXN003338,FL-105,2024-09-17 10:06:00,TOILETPAPER12,Toilet Paper 12-Roll,Household Essentials,2,10.47
3,TXN025020,FL-330,2024-09-11 06:29:08,ROKU-STD,Roku Streaming Stick,ELECTRONICS,1,28.59
4,TXN015797,FL-302,2024-09-26 15:59:42,BEER-24,Light Beer 24pk,Alcoholic Beverages,3,18.82
...,...,...,...,...,...,...,...,...
25557,TXN020201,FL-105,2024-09-03T18:28:07,DIAPERS-3,Diapers Size 3,baby,2,24.32
25558,TXN014835,FL-239,09-26-2024 08:47:08,CARDS-01,Playing Cards,Games & Entertainment,3,5.00
25559,TXN002434,fl-239,16-Sep-2024 16:39,PAPERTOWEL6,Paper Towels 6-Roll,household,2,7.78
25560,TXN014739,FL-710,2024-09-25 17:08:35,CHRG-PORT,PORTABLE CHARGER,electronics,1,24.18
25561,TXN010981,FL-105,24-Sep-2024 06:32,DIAP-S3,Diapers Size 3,baby,2,24.90

**Handling Timestamp**

In [62]:
walmart_transactions_copy['timestamp'] = pd.to_datetime(walmart_transactions_copy['timestamp'],errors='coerce', format ='mixed')
missing_date = walmart_transactions_copy['timestamp'].isna().sum()
print('count failed timestamps :',missing_date)

walmart_transactions_copy['hour'] = walmart_transactions_copy['timestamp'].dt.hour
walmart_transactions_copy[walmart_transactions_copy['timestamp'].isna()]

count failed timestamps : 884

,transaction_id,store_id,timestamp,sku,product_name,category,quantity,unit_price,hour
24,TXN006442,FL-710,NaT,PAPERTOWEL6,Paper Towels,Household,1,7.82,NaN
45,TXN021737,FL-619,NaT,TP-12,TOILET PAPER 12PK,HOUSEHOLD,2,9.74,NaN
46,TXN017349,FL-501,NaT,CANDLE-EMRG,Emergency Candles,emergency,1,5.78,NaN
83,TXN019304,FL-619,NaT,BATT-100,BATTERIES AA 4PK,Emergency,1,6.56,NaN
138,TXN012731,FL_239,NaT,PT-12,POPTART-STRAWBERRY,BREAKFAST,4,3.56,NaN
...,...,...,...,...,...,...,...,...,...
25505,TXN022501,fl-239,NaT,BATT_AA_4PK,AA Batteries (4-pack),emergency,1,6.28,NaN
25508,TXN022939,FL-619,NaT,HDTARP-01,HD Tarp,emergency,2,20.07,NaN
25548,TXN005477,fl-445,NaT,LED-FLASH,LED Flashlight,emergency,1,13.35,NaN
25549,TXN003817,FL-619,NaT,BFORM-01,BABY FORMULA,BABY,1,28.78,NaN
25552,TXN010660,FL-710,NaT,BFORM-01,Infant Formula,BABY,1,29.67,NaN

In [63]:
table_info(walmart_transactions_copy)

Table infor:
<class 'pandas.core.frame.DataFrame'>
Index: 25532 entries, 0 to 25561
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   transaction_id  25532 non-null  object
 1   store_id        25532 non-null  object
 2   timestamp       24648 non-null  datetime64[ns]
 3   sku             25532 non-null  object
 4   product_name    25532 non-null  object
 5   category        25532 non-null  object
 6   quantity        25532 non-null  int64
 7   unit_price      25532 non-null  float64
 8   hour            24648 non-null  float64
dtypes: datetime64[ns](1), float64(2), int64(1), object(5)
memory usage: 1.9+ MB

Null values for each column

transaction_id      0
store_id            0
timestamp         884
sku                 0
product_name        0
category            0
quantity            0
unit_price          0
hour              884
dtype: int64

Duplicated Rows Count:  0

**Handling NaN for the cost_per_shipment**

In [64]:
distribution_centers_copy

,dc_id,dc_name,city,state,avg_daily_shipments,surge_capacity,distance_to_orlando_mi,cost_per_shipment
0,DC-JAX,Jacksonville Distribution Center,Jacksonville,FL,500,1000,141,245.0
1,DC-ATL,Atlanta Distribution Center,Atlanta,GA,400,700,438,412.5
2,DC-DAL,Dallas Distribution Center,Dallas,TX,300,600,1108,687.0
3,DC-MIA,Miami Distribution Center,Miami,FL,350,~750,235,298.0
4,DC-BHM,Birmingham Distribution Center,Birmingham,AL,250,500,503,NaN

In [65]:
missing_cost_per_shipment =  distribution_centers_copy['cost_per_shipment'].isna().sum()
distribution_centers_copy['cost_per_shipment'] = distribution_centers_copy['cost_per_shipment'].fillna(distribution_centers_copy['cost_per_shipment'].median())
log_decision('Filling missing values in cost per shipment column with the median of all cost of shipments',missing_cost_per_shipment)

Filling missing values in cost per shipment column with the median of all cost of shipments(1 row(s))

**Handling NaN for the latitude and longitute**

**Handling NaN for the subcategory**

In [66]:
product_catalog_copy_with_na_sum = len(product_catalog_copy[product_catalog_copy['subcategory'].isna()])

SUBC_MAP = {
    'pop-tarts strawberry': 'Pop-Tarts',
    'Pop-Tarts Strawberry': 'Pop-Tarts',
    'Water - 24 Pack': 'Bottled',
    'FLASHLIGHT LED':'Flashlight',
    'Light Beer (24-pack)':'Light',
    'Monopoly Board Game':'Playing',
    'Board Game - Monopoly': 'Playing',
    'Canned Soup':'Canned',
    'First Aid Kit':'First',
    'PORTABLE CHARGER':'Portable',
    'Baby Formula':'Baby',
    'Heavy Duty Tarp': 'Tarp'

}

product_catalog_copy['subcategory'] = product_catalog_copy['subcategory'].fillna(product_catalog_copy['product_name'].map(SUBC_MAP))
log_decision('Filled missing values in the subcategory column with mapped categories',product_catalog_copy_with_na_sum)

Filled missing values in the subcategory column with mapped categories(13 row(s))

**TODO: Fixing inventory_and_sales.db File**

In [67]:
import sqlite3
db_path = '/content/walmart-hurricane-project/data/inventory_and_sales.db'
conn = sqlite3.connect(db_path)
tables = pd.read_sql_query(
    "SELECT name FROM sqlite_master WHERE type='table'",
    conn)
display(tables)

                  name
0  daily_sales_summary
1     inventory_levels

In [68]:
daily_sales = pd.read_sql_query("SELECT * FROM daily_sales_summary", conn)
inventory = pd.read_sql_query("SELECT * FROM inventory_levels", conn)
print("DAILY SALES SUMMARY")
table_info(daily_sales)
print("INVENTORY LEVELS")
table_info(inventory)

DAILY SALES SUMMARY

Table infor:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3600 entries, 0 to 3599
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           3600 non-null   object
 1   store_id       3600 non-null   object
 2   category       3600 non-null   object
 3   total_units    3600 non-null   float64
 4   total_revenue  3600 non-null   float64
dtypes: float64(2), object(3)
memory usage: 140.8+ KB

Null values for each column

date             0
store_id         0
category         0
total_units      0
total_revenue    0
dtype: int64

Duplicated Rows Count:  0
INVENTORY LEVELS

Table infor:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4320 entries, 0 to 4319
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   date            4320 non-null   object
 1   store_id        4320 non-null   object
 2   sku             4320 non-null   object
 3   units_on_hand   4320 non-null   int64
 4   units_on_order  3694 non-null   float64
 5   reorder_point   4320 non-null   int64
dtypes: float64(1), int64(2), object(3)
memory usage: 202.6+ KB

Null values for each column

date                0
store_id            0
sku                 0
units_on_hand       0
units_on_order    626
reorder_point       0
dtype: int64

Duplicated Rows Count:  0

In [69]:
print(inventory[inventory['units_on_order'].isna()].head(10))
print(inventory['units_on_order'].describe())

          date store_id            sku  units_on_hand  units_on_order  \
33  2024-09-12   FL-330      CNSOUP-01            122             NaN
37  2024-09-12   FL-412     PNUTBTR-16            199             NaN
38  2024-09-12   FL-412      CHRG-PORT            129             NaN
54  2024-09-12   FL-287  TOILETPAPER12             94             NaN
55  2024-09-12   FL-287       WTR_24PK            102             NaN
58  2024-09-12   FL-287      HDTARP-01            190             NaN
59  2024-09-12   FL-287    BATT_AA_4PK             61             NaN
67  2024-09-12   FL-156       MISC-001            195             NaN
83  2024-09-12   FL-501  PT_STRAWBERRY             96             NaN
89  2024-09-12   FL-078         WTR-24            197             NaN

    reorder_point
33             21
37             42
38             40
54             40
55             49
58             21
59             22
67             24
83             33
89             50
count    3694.000000
mean       49.783703
std        29.198093
min         0.000000
25%        25.000000
50%        50.000000
75%        75.000000
max       100.000000
Name: units_on_order, dtype: float64

In [70]:
print("DAILY SALES DATES")
print(daily_sales['date'].unique())
print("INVENTORY DATES")
print(inventory['date'].unique())
print("DAILY SALES STORE IDS")
print(sorted(daily_sales['store_id'].unique()))
print("INVENTORY STORE IDS")
print(sorted(inventory['store_id'].unique()))

DAILY SALES DATES
['2024-09-12' '20240912' '2024-09-13' '20240913' '2024-09-14' '20240914'
 '2024-09-15' '20240915' '2024-09-16' '20240916' '2024-09-17' '20240917'
 '2024-09-18' '20240918' '2024-09-19' '20240919' '2024-09-20' '20240920'
 '2024-09-21' '20240921' '2024-09-22' '20240922' '2024-09-23' '20240923'
 '2024-09-24' '20240924' '2024-09-25' '20240925' '2024-09-26' '20240926'
 '2024-09-27' '20240927' '2024-09-28' '20240928' '2024-09-29' '20240929'
 '2024-09-30' '20240930' '2024-09-01' '20240901' '2024-09-02' '20240902'
 '2024-09-03' '20240903' '2024-09-04' '20240904' '2024-09-05' '20240905'
 '2024-09-06' '20240906' '2024-09-07' '20240907' '2024-09-08' '20240908'
 '2024-09-09' '20240909' '2024-09-10' '20240910' '2024-09-11' '20240911']
INVENTORY DATES
['2024-09-12' '2024-09-13' '2024-09-14' '2024-09-15' '2024-09-16'
 '2024-09-17' '2024-09-18' '2024-09-19' '2024-09-20' '2024-09-21'
 '2024-09-22' '2024-09-23' '2024-09-24' '2024-09-25' '2024-09-26'
 '2024-09-27' '2024-09-28' '2024-09-29' '2024-09-30' '2024-09-01'
 '2024-09-02' '2024-09-03' '2024-09-04' '2024-09-05' '2024-09-06'
 '2024-09-07' '2024-09-08' '2024-09-09' '2024-09-10' '2024-09-11']
DAILY SALES STORE IDS
['FL-078', 'FL-105', 'FL-156', 'FL-239', 'FL-287', 'FL-302', 'FL-330', 'FL-412', 'FL-445', 'FL-501', 'FL-619', 'FL-710']
INVENTORY STORE IDS
['FL-078', 'FL-105', 'FL-156', 'FL-239', 'FL-287', 'FL-302', 'FL-330', 'FL-412', 'FL-445', 'FL-501', 'FL-619', 'FL-710']

In [71]:
daily_sales_copy = daily_sales.copy()
inventory_copy = inventory.copy()
daily_sales_copy['date'] = pd.to_datetime(daily_sales_copy['date'], format='mixed', errors='coerce')
inventory_copy['date'] = pd.to_datetime(inventory_copy['date'], errors='coerce')
print("Missing dates after conversion:", daily_sales_copy['date'].isna().sum(), inventory_copy['date'].isna().sum())
print(daily_sales_copy['date'].head())

Missing dates after conversion: 0 0
0   2024-09-12
1   2024-09-12
2   2024-09-12
3   2024-09-12
4   2024-09-12
Name: date, dtype: datetime64[ns]

In [72]:
changed_dates = (daily_sales['date'] != daily_sales_copy['date'].dt.strftime('%Y-%m-%d')).sum()
log_decision("Standardized database dates to datetime format", changed_dates)

Standardized database dates to datetime format(218 row(s))

In [73]:
print(inventory_copy.groupby('date')['units_on_order'].apply(lambda x: x.isna().sum()))

date
2024-09-01    26
2024-09-02    19
2024-09-03    15
2024-09-04    15
2024-09-05    29
2024-09-06    27
2024-09-07    15
2024-09-08    20
2024-09-09    20
2024-09-10    23
2024-09-11    26
2024-09-12    14
2024-09-13    19
2024-09-14    23
2024-09-15    20
2024-09-16    22
2024-09-17    19
2024-09-18    31
2024-09-19    23
2024-09-20    26
2024-09-21    20
2024-09-22    20
2024-09-23    15
2024-09-24    24
2024-09-25    23
2024-09-26    23
2024-09-27    22
2024-09-28    15
2024-09-29    20
2024-09-30    12
Name: units_on_order, dtype: int64

In [74]:
missing_orders = inventory_copy['units_on_order'].isna().sum()
log_decision("Kept missing units_on_order values as NaN because order quantities are unknown", missing_orders)

Kept missing units_on_order values as NaN because order quantities are unknown(626 row(s))

In [75]:
print("NEGATIVE INVENTORY VALUES")
print((inventory_copy[['units_on_hand', 'units_on_order', 'reorder_point']] < 0).sum())
print("NEGATIVE DAILY SALES VALUES")
print((daily_sales_copy[['total_units', 'total_revenue']] < 0).sum())

NEGATIVE INVENTORY VALUES
units_on_hand     0
units_on_order    0
reorder_point     0
dtype: int64
NEGATIVE DAILY SALES VALUES
total_units       0
total_revenue    34
dtype: int64

In [76]:
negative_revenue = daily_sales_copy[daily_sales_copy['total_revenue'] < 0]
print(negative_revenue.to_string(index=False))

      date store_id      category  total_units  total_revenue
2024-09-13   FL-619       Grocery         45.0        -511.85
2024-09-14   FL-412          Baby         63.0        -636.73
2024-09-14   FL-445 Entertainment         42.0        -230.35
2024-09-16   FL-105     Breakfast         72.0        -857.40
2024-09-18   FL-330       Alcohol         76.0       -1404.17
2024-09-18   FL-078     Breakfast         91.0       -1336.09
2024-09-19   FL-287 Entertainment         39.0        -698.65
2024-09-19   FL-302 Entertainment         90.0       -1421.10
2024-09-20   FL-330        Snacks         44.0        -428.43
2024-09-20   FL-156       Grocery         60.0        -477.34
2024-09-20   FL-445     Emergency        131.0       -1877.10
2024-09-21   FL-501     Emergency        200.0       -3250.54
2024-09-21   FL-078       Alcohol         80.0       -1585.93
2024-09-23   FL-619     Emergency         77.0       -1015.24
2024-09-24   FL-302       Grocery         96.0       -1424.03
2024-09-26   FL-105     Household         23.0        -128.24
2024-09-26   FL-412     Emergency        111.0       -1716.34
2024-09-27   FL-105          Baby         49.0        -516.31
2024-09-27   FL-412       Grocery         42.0        -639.03
2024-09-28   FL-501       Alcohol         77.0       -1040.65
2024-09-28   FL-710       Grocery         24.0        -446.05
2024-09-29   FL-619          Baby         48.0        -909.33
2024-09-30   FL-330        Health         68.0        -826.75
2024-09-30   FL-619       Alcohol         61.0        -687.98
2024-09-30   FL-710       Grocery         53.0        -332.28
2024-09-02   FL-330     Emergency         58.0        -484.96
2024-09-04   FL-302   Electronics         74.0        -546.71
2024-09-07   FL-287   Electronics         41.0        -576.70
2024-09-07   FL-287          Baby         52.0        -965.37
2024-09-07   FL-156     Breakfast         72.0       -1308.49
2024-09-09   FL-287 Entertainment         15.0         -52.68
2024-09-10   FL-619     Emergency         87.0       -1204.55
2024-09-11   FL-078     Breakfast         51.0        -561.66
2024-09-11   FL-619     Household         60.0        -526.24

In [77]:
print("NEGATIVE TRANSACTION PRICES")
print((walmart_transactions_copy['unit_price'] < 0).sum())
print("NEGATIVE TRANSACTION QUANTITIES")
print((walmart_transactions_copy['quantity'] < 0).sum())

NEGATIVE TRANSACTION PRICES
0
NEGATIVE TRANSACTION QUANTITIES
130

In [78]:
negative_transactions = walmart_transactions_copy[walmart_transactions_copy['quantity'] < 0]
print(negative_transactions[['store_id', 'timestamp', 'product_name', 'category', 'quantity', 'unit_price']].head(10).to_string(index=False))

store_id           timestamp          product_name           category  quantity  unit_price
  FL-078 2024-09-22 21:30:35          Paper Towels          HOUSEHOLD        -2        7.91
  FL-619 2024-09-20 17:10:14        Diapers Size 3               baby        -2       25.79
  FL-330 2024-09-25 11:32:05 Board Game - Monopoly      ENTERTAINMENT        -2       19.58
  FL-287 2024-09-06 13:20:05            TP 12 Pack          household        -2        9.64
  FL-619 2024-09-30 14:42:48         First-Aid Kit             Health        -2       14.45
  fl-619 2024-09-24 10:06:37       Heavy Duty Tarp          Emergency        -1       19.46
  FL-501 2024-09-19 08:16:33       Heavy Duty Tarp Emergency Supplies        -1       19.00
  FL-287 2024-09-16 07:26:23          Baby Formula               baby        -2       28.53
  FL-412                 NaT  Variety Pack - Chips             SNACKS        -1        8.70
  FL-445 2024-09-24 21:07:01         First Aid Kit             Health        -2       15.61

In [79]:
negative_revenue_count = (daily_sales_copy['total_revenue'] < 0).sum()
log_decision("Kept negative revenue values for further investigation because they may represent returns or adjustments", negative_revenue_count)

Kept negative revenue values for further investigation because they may represent returns or adjustments(34 row(s))

In [80]:
print("FINAL DAILY SALES CHECK")
table_info(daily_sales_copy)
print("FINAL INVENTORY CHECK")
table_info(inventory_copy)
print("DATABASE CLEANING DECISIONS")
show_log()

FINAL DAILY SALES CHECK

Table infor:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3600 entries, 0 to 3599
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           3600 non-null   datetime64[ns]
 1   store_id       3600 non-null   object
 2   category       3600 non-null   object
 3   total_units    3600 non-null   float64
 4   total_revenue  3600 non-null   float64
dtypes: datetime64[ns](1), float64(2), object(2)
memory usage: 140.8+ KB

Null values for each column

date             0
store_id         0
category         0
total_units      0
total_revenue    0
dtype: int64

Duplicated Rows Count:  0
FINAL INVENTORY CHECK

Table infor:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4320 entries, 0 to 4319
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   date            4320 non-null   datetime64[ns]
 1   store_id        4320 non-null   object
 2   sku             4320 non-null   object
 3   units_on_hand   4320 non-null   int64
 4   units_on_order  3694 non-null   float64
 5   reorder_point   4320 non-null   int64
dtypes: datetime64[ns](1), float64(1), int64(2), object(2)
memory usage: 202.6+ KB

Null values for each column

date                0
store_id            0
sku                 0
units_on_hand       0
units_on_order    626
reorder_point       0
dtype: int64

Duplicated Rows Count:  0
DATABASE CLEANING DECISIONS

                                            decision  rows
0  Filling missing values in cost per shipment co...     1
1  Filled missing values in the subcategory colum...    13
2     Standardized database dates to datetime format   218
3  Kept missing units_on_order values as NaN beca...   626
4  Kept negative revenue values for further inves...    34

### **Dates and Categories Cleaning**

**Inspecting Dates and Categories**

In [81]:
print("Walmart Transactions:")
print(walmart_transactions_copy[['transaction_date', 'category']].head() if 'transaction_date' in walmart_transactions_copy.columns else walmart_transactions_copy.columns.tolist())
print("\nDaily Sales:")
print(daily_sales_copy[['date', 'category']].head())

Walmart Transactions:
['transaction_id', 'store_id', 'timestamp', 'sku', 'product_name', 'category', 'quantity', 'unit_price', 'hour']

Daily Sales:
        date       category
0 2024-09-12      Emergency
1 2024-09-12      Breakfast
2 2024-09-12        Alcohol
3 2024-09-12  Entertainment
4 2024-09-12        Grocery

In [82]:
print("Walmart Transactions:")
print(walmart_transactions_copy[['timestamp', 'category']].head())
print("\nWalmart Categories:")
print(walmart_transactions_copy['category'].unique())
print("\nDaily Sales Categories:")
print(daily_sales_copy['category'].unique())

Walmart Transactions:
            timestamp              category
0 2024-09-24 09:48:13               Grocery
1 2024-09-13 20:30:20               GROCERY
2 2024-09-17 10:06:00  Household Essentials
3 2024-09-11 06:29:08           ELECTRONICS
4 2024-09-26 15:59:42   Alcoholic Beverages

Walmart Categories:
['Grocery' 'GROCERY' 'Household Essentials' 'ELECTRONICS'
 'Alcoholic Beverages' 'snacks' 'Emergency' 'Household' 'electronics'
 'EMERGENCY' 'entertainment' 'SNACKS' 'ENTERTAINMENT' 'ALCOHOL' 'Health'
 'BREAKFAST' 'Alcohol' 'Groceries' 'emergency' 'Breakfast' 'Baby Products'
 'household' 'Electronics' 'Emergency Supplies' 'Entertainment'
 'HOUSEHOLD' 'BABY' 'baby' 'grocery' 'Games & Entertainment' 'Snacks'
 'Baby' 'HEALTH' 'health' 'breakfast' 'Breakfast Foods'
 'Health & Wellness']

Daily Sales Categories:
['Emergency' 'Breakfast' 'Alcohol' 'Entertainment' 'Grocery' 'Electronics'
 'Snacks' 'Household' 'Health' 'Baby']

**Standardizing Category Capitalization and Spacing**

In [83]:
walmart_transactions_copy['category'] = walmart_transactions_copy['category'].str.strip().str.title()
daily_sales_copy['category'] = daily_sales_copy['category'].str.strip().str.title()
print("Walmart Categories:")
print(walmart_transactions_copy['category'].unique())
print("\nDaily Sales Categories:")
print(daily_sales_copy['category'].unique())

Walmart Categories:
['Grocery' 'Household Essentials' 'Electronics' 'Alcoholic Beverages'
 'Snacks' 'Emergency' 'Household' 'Entertainment' 'Alcohol' 'Health'
 'Breakfast' 'Groceries' 'Baby Products' 'Emergency Supplies' 'Baby'
 'Games & Entertainment' 'Breakfast Foods' 'Health & Wellness']

Daily Sales Categories:
['Emergency' 'Breakfast' 'Alcohol' 'Entertainment' 'Grocery' 'Electronics'
 'Snacks' 'Household' 'Health' 'Baby']

**Checking Category Counts and Differences**

In [84]:
print("Walmart Category Counts:")
print(walmart_transactions_copy['category'].value_counts())
print("\nDaily Sales Category Counts:")
print(daily_sales_copy['category'].value_counts())

Walmart Category Counts:
category
Emergency                5371
Electronics              2522
Grocery                  2451
Entertainment            1893
Emergency Supplies       1819
Household                1779
Baby                     1589
Breakfast                1569
Snacks                    979
Health                    937
Alcohol                   864
Groceries                 858
Games & Entertainment     645
Household Essentials      571
Baby Products             497
Breakfast Foods           493
Alcoholic Beverages       401
Health & Wellness         294
Name: count, dtype: int64

Daily Sales Category Counts:
category
Emergency        360
Breakfast        360
Alcohol          360
Entertainment    360
Grocery          360
Electronics      360
Snacks           360
Household        360
Health           360
Baby             360
Name: count, dtype: int64

In [85]:
walmart_categories = set(walmart_transactions_copy['category'].dropna().unique())
daily_categories = set(daily_sales_copy['category'].dropna().unique())
print("Categories not found in Daily Sales:")
print(sorted(walmart_categories - daily_categories))

Categories not found in Daily Sales:
['Alcoholic Beverages', 'Baby Products', 'Breakfast Foods', 'Emergency Supplies', 'Games & Entertainment', 'Groceries', 'Health & Wellness', 'Household Essentials']

**Mapping Categories to Standard Names**

In [86]:
category_mapping = {
    'Alcoholic Beverages': 'Alcohol',
    'Baby Products': 'Baby',
    'Breakfast Foods': 'Breakfast',
    'Emergency Supplies': 'Emergency',
    'Games & Entertainment': 'Entertainment',
    'Groceries': 'Grocery',
    'Health & Wellness': 'Health',
    'Household Essentials': 'Household'
}
walmart_transactions_copy['category'] = walmart_transactions_copy['category'].replace(category_mapping)
print("Updated Walmart Categories:")
print(walmart_transactions_copy['category'].unique())

Updated Walmart Categories:
['Grocery' 'Household' 'Electronics' 'Alcohol' 'Snacks' 'Emergency'
 'Entertainment' 'Health' 'Breakfast' 'Baby']

**Validating Category Cleaning Results**

In [87]:
walmart_categories = set(walmart_transactions_copy['category'].dropna().unique())
daily_categories = set(daily_sales_copy['category'].dropna().unique())
print("Walmart category count:", len(walmart_categories))
print("Daily Sales category count:", len(daily_categories))
print("Categories match:", walmart_categories == daily_categories)
print("Missing Walmart categories:", walmart_transactions_copy['category'].isna().sum())

Walmart category count: 10
Daily Sales category count: 10
Categories match: True
Missing Walmart categories: 0

**Documenting Category Cleaning Decisions**

In [88]:
log_decision("Standardized Walmart category capitalization and spacing, and mapped 8 category names to match Daily Sales (pending team confirmation)", len(walmart_transactions_copy))
show_log()

Standardized Walmart category capitalization and spacing, and mapped 8 category names to match Daily Sales (pending team confirmation)(25532 row(s))

                                            decision   rows
0  Filling missing values in cost per shipment co...      1
1  Filled missing values in the subcategory colum...     13
2     Standardized database dates to datetime format    218
3  Kept missing units_on_order values as NaN beca...    626
4  Kept negative revenue values for further inves...     34
5  Standardized Walmart category capitalization a...  25532

**Checking Date Formats and Missing Values**

In [90]:
print("Walmart timestamp type:")
print(walmart_transactions_copy['timestamp'].dtype)
print("\nDaily Sales date type:")
print(daily_sales_copy['date'].dtype)
print("\nMissing Walmart timestamps:")
print(walmart_transactions_copy['timestamp'].isna().sum())
print("\nMissing Daily Sales dates:")
print(daily_sales_copy['date'].isna().sum())

Walmart timestamp type:
datetime64[ns]

Daily Sales date type:
datetime64[ns]

Missing Walmart timestamps:
884

Missing Daily Sales dates:
0

**Investigate Missing Walmart Timestamps**

In [91]:
print("Transactions with missing timestamps:")
print(walmart_transactions_copy[walmart_transactions_copy['timestamp'].isna()].head())
print("\nTotal Walmart transactions:")
print(len(walmart_transactions_copy))

Transactions with missing timestamps:
    transaction_id store_id timestamp          sku        product_name  \
24       TXN006442   FL-710       NaT  PAPERTOWEL6        Paper Towels
45       TXN021737   FL-619       NaT        TP-12   TOILET PAPER 12PK
46       TXN017349   FL-501       NaT  CANDLE-EMRG   Emergency Candles
83       TXN019304   FL-619       NaT     BATT-100    BATTERIES AA 4PK
138      TXN012731   FL_239       NaT        PT-12  POPTART-STRAWBERRY

      category  quantity  unit_price  hour
24   Household         1        7.82   NaN
45   Household         2        9.74   NaN
46   Emergency         1        5.78   NaN
83   Emergency         1        6.56   NaN
138  Breakfast         4        3.56   NaN

Total Walmart transactions:
25532

In [92]:
missing_ids = walmart_transactions_copy.loc[walmart_transactions_copy['timestamp'].isna(), 'transaction_id']
print("Original timestamps for affected transactions:")
print(walmart_transactions[walmart_transactions['transaction_id'].isin(missing_ids)][['transaction_id', 'timestamp']].head(10))

Original timestamps for affected transactions:
    transaction_id timestamp
24       TXN006442       NaN
45       TXN021737       NaN
46       TXN017349       NaN
83       TXN019304       NaN
138      TXN012731       NaN
146      TXN007423       NaN
147      TXN020494       NaN
174      TXN014455       NaN
207      TXN003954       NaN
225      TXN003573       NaN

In [93]:
original_missing = walmart_transactions[walmart_transactions['transaction_id'].isin(missing_ids)]
print("Missing timestamps in cleaned data:", len(missing_ids))
print("Originally missing timestamps:", original_missing['timestamp'].isna().sum())
print("Original timestamps with values:", original_missing['timestamp'].notna().sum())

Missing timestamps in cleaned data: 884
Originally missing timestamps: 886
Original timestamps with values: 0

In [94]:
print("Original missing timestamps:", walmart_transactions['timestamp'].isna().sum())
print("Cleaned missing timestamps:", walmart_transactions_copy['timestamp'].isna().sum())
print("Original transaction rows:", len(walmart_transactions))
print("Cleaned transaction rows:", len(walmart_transactions_copy))
print("Original duplicate rows:", walmart_transactions.duplicated().sum())

Original missing timestamps: 886
Cleaned missing timestamps: 884
Original transaction rows: 25562
Cleaned transaction rows: 25532
Original duplicate rows: 30

**Documenting Missing Timestamp Decisions**

In [95]:
log_decision("Kept 884 missing Walmart timestamps as NaT because original dates were missing; retained transactions for other analysis", 884)
show_log()

Kept 884 missing Walmart timestamps as NaT because original dates were missing; retained transactions for other analysis(884 row(s))

                                            decision   rows
0  Filling missing values in cost per shipment co...      1
1  Filled missing values in the subcategory colum...     13
2     Standardized database dates to datetime format    218
3  Kept missing units_on_order values as NaN beca...    626
4  Kept negative revenue values for further inves...     34
5  Standardized Walmart category capitalization a...  25532
6  Kept 884 missing Walmart timestamps as NaT bec...    884

**Checking Sales Timezone**

In [96]:
print("Walmart timestamp timezone:")
print(walmart_transactions_copy['timestamp'].dt.tz)
print("\nWalmart transaction dates:")
print(walmart_transactions_copy['timestamp'].min())
print(walmart_transactions_copy['timestamp'].max())
print("\nStore locations:")
print(store_locations_copy.columns.tolist())
print(store_locations_copy.head())

Walmart timestamp timezone:
None

Walmart transaction dates:
2024-09-01 06:01:15
2024-09-30 22:57:47

Store locations:
['store_id', 'store_name', 'city', 'state', 'zip_code', 'latitude', 'longitude', 'region']
  store_id                             store_name          city    state  \
0   FL-239            Walmart Supercenter Orlando       Orlando       FL
1   FL-105              Walmart Supercenter Tampa         Tampa       FL
2   FL-330              Walmart Supercenter Miami         Miami       FL
3   FL-412       Walmart Supercenter Jacksonville  Jacksonville       FL
4   FL-287  Walmart Neighborhood Market Kissimmee     Kissimmee  Florida

   zip_code  latitude  longitude   region
0     32801   28.5383   -81.3792  Central
1     33602   27.9506   -82.4572     West
2     33101   25.7617   -80.1918    South
3     32099   30.3322   -81.6557    North
4     34741   28.2920   -81.4076  Central

In [97]:
print("Store cities and states:")
print(store_locations_copy[['city', 'state']].drop_duplicates())
print("\nStore IDs:")
print(store_locations_copy['store_id'].unique())

Store cities and states:
              city    state
0          Orlando       FL
1            Tampa       FL
2            Miami       FL
3     Jacksonville       FL
4        Kissimmee  Florida
5    Daytona Beach       FL
6       Fort Myers       FL
7      Gainesville       FL
8      Tallahassee       FL
9   St. Petersburg     Fla.
10        Lakeland  Florida
11       Pensacola       FL

Store IDs:
['FL-239' 'FL-105' 'FL-330' 'FL-412' 'FL-287' 'FL-156' 'FL-501' 'FL-078'
 'FL-619' 'FL-445' 'FL-302' 'FL-710' 'FL239' 'FL_287']

In [98]:
print("Pensacola stores:")
print(store_locations_copy[store_locations_copy['city'] == 'Pensacola'][['store_id', 'city', 'state']])
print("\nPensacola transaction counts:")
print(walmart_transactions_copy['store_id'].value_counts())

Pensacola stores:
   store_id       city state
11   FL-710  Pensacola    FL

Pensacola transaction counts:
store_id
FL-445     1816
FL-156     1805
FL-710     1804
FL-105     1798
FL-412     1783
FL-302     1775
FL-330     1770
FL-287     1748
FL-078     1741
FL-501     1728
FL-239     1724
FL-619     1695
FL_302      150
FL_239      140
FL_619      133
FL_287      131
FL_330      131
FL_445      130
FL_078      127
FL_412      123
FL_501      123
FL_156      122
FL_105      119
FL_710      118
FL287       102
fl-287      100
FL239        96
fl-501       95
FL445        95
fl-302       94
fl-156       93
fl-330       91
fl-710       89
fl-105       89
FL302        89
fl-239       88
fl-619       87
FL619        85
FL156        84
FL078        82
FL501        81
fl-445       80
 FL-330      78
 FL-302      78
fl-412       77
FL412        76
FL330        75
FL105        73
fl-078       73
 FL-710      72
 FL-619      68
FL710        66
 FL-156      62
 FL-287      59
 FL-078      57
 FL-412      56
 FL-105      53
 FL-445      53
 FL-239      52
 FL-501      50
Name: count, dtype: int64

**Determining the Sales Timezone**

In [99]:
# Sales timestamps have no timezone set. Need to confirm Eastern time before joining with weather data.

In [100]:
walmart_transactions_copy['timestamp'] = walmart_transactions_copy['timestamp'].dt.tz_localize('America/New_York')
print("Walmart timezone:")
print(walmart_transactions_copy['timestamp'].dt.tz)
print("Missing timestamps:", walmart_transactions_copy['timestamp'].isna().sum())

Walmart timezone:
America/New_York
Missing timestamps: 884

In [101]:
print("Daily Sales date type:")
print(daily_sales_copy['date'].dtype)
print("\nDaily Sales date range:")
print(daily_sales_copy['date'].min())
print(daily_sales_copy['date'].max())
print("\nMissing Daily Sales dates:")
print(daily_sales_copy['date'].isna().sum())

Daily Sales date type:
datetime64[ns]

Daily Sales date range:
2024-09-01 00:00:00
2024-09-30 00:00:00

Missing Daily Sales dates:
0

In [103]:
# Kept Daily Sales dates as they are because they are already in datetime format with no missing values.